# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'university-parking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'LGButton'
  pod 'Alamofire', '~> 5.0.0-rc.2'

end
